spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/sampleData
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  server:
    compression:
      enabled: true
    servlet:
      context-path: /softcaribbean

  security:
    user:
      name: test
      password: test
